[build]
  command = "cd bowerycreativefrontend && npm ci && npm run build"
  publish = "bowerycreativefrontend/dist"
  # Skip builds when only Mission Control or non-code files change
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . '../mission-control/**' '../**.md' '../**.sql' '../docs/**'"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200