[build]
  command = "cd bowerycreativefrontend && npm ci && npm run build"
  publish = "bowerycreativefrontend/dist"
  # Force build always

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200