[build]
  base = "payments"
  publish = "dist"
  command = "npm run build"
  # Skip all builds - this app is now integrated into main site
  ignore = "exit 0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"