// Client Email Configuration System
// For custom domains managed by Bowery Creative

export const clientEmails = {
  // Dr. Greg Pedro Practice Domain
  'gregpedromd.com': {
    domain: 'gregpedromd.com',
    client: 'Dr. Greg Pedro Practice',
    managedBy: 'Bowery Creative Agency',
    
    // Email accounts on this domain
    accounts: {
      cindi: {
        email: 'cindi@gregpedromd.com',
        name: 'Cindi Weiss',
        title: 'Practice Manager',
        department: 'Administration',
        forwardTo: null, // Direct mailbox, not forwarded
        status: 'active',
        canSend: true,
        canReceive: true,
        created: '2025-01-16',
        features: [
          'Full IMAP/POP3 access',
          'SMTP sending',
          'Webmail interface',
          'Mobile device sync',
          'Calendar integration',
          'Contact management'
        ]
      },
      greg: {
        email: 'greg@gregpedromd.com',
        name: 'Dr. Greg Pedro',
        title: 'Doctor',
        department: 'Clinical',
        forwardTo: null,
        status: 'pending', // To be configured if needed
        canSend: true,
        canReceive: true,
        features: [
          'Full IMAP/POP3 access',
          'SMTP sending',
          'Webmail interface',
          'Mobile device sync',
          'HIPAA-compliant encryption'
        ]
      },
      info: {
        email: 'info@gregpedromd.com',
        name: 'Dr. Greg Pedro Practice',
        title: 'General Information',
        department: 'Reception',
        forwardTo: 'cindi@gregpedromd.com',
        status: 'active',
        canSend: true,
        canReceive: true,
        features: ['Contact form submissions', 'General inquiries']
      },
      appointments: {
        email: 'appointments@gregpedromd.com',
        name: 'Dr. Greg Pedro Practice',
        title: 'Appointment Scheduling',
        department: 'Scheduling',
        forwardTo: 'cindi@gregpedromd.com',
        status: 'active',
        canSend: true,
        canReceive: true,
        features: ['Appointment requests', 'Scheduling confirmations']
      }
    },
    
    // Email server configuration
    serverConfig: {
      // IMAP Settings (for receiving)
      imap: {
        server: 'mail.gregpedromd.com',
        port: 993,
        encryption: 'SSL/TLS',
        authentication: 'Username/Password'
      },
      
      // SMTP Settings (for sending)
      smtp: {
        server: 'mail.gregpedromd.com',
        port: 587,
        encryption: 'STARTTLS',
        authentication: 'Username/Password'
      },
      
      // Webmail Access
      webmail: {
        url: 'https://webmail.gregpedromd.com',
        interface: 'Roundcube/cPanel',
        mobileOptimized: true
      }
    },
    
    // DNS Records (for technical setup)
    dnsRecords: {
      mx: [
        { priority: 10, server: 'mail.gregpedromd.com' }
      ],
      a: [
        { subdomain: 'mail', ip: 'TBD' }
      ],
      cname: [
        { subdomain: 'webmail', target: 'mail.gregpedromd.com' }
      ],
      txt: [
        { type: 'SPF', value: 'v=spf1 include:mail.gregpedromd.com ~all' },
        { type: 'DKIM', value: 'TBD - Generated by email provider' },
        { type: 'DMARC', value: 'v=DMARC1; p=quarantine; rua=mailto:cindi@gregpedromd.com' }
      ]
    }
  }
};

// Helper functions for client email management
export const clientEmailHelpers = {
  
  // Get email configuration for a specific account
  getEmailAccount(domain, account) {
    const domainConfig = clientEmails[domain];
    if (!domainConfig) {
      throw new Error(`Domain ${domain} not configured`);
    }
    
    const accountConfig = domainConfig.accounts[account];
    if (!accountConfig) {
      throw new Error(`Account ${account}@${domain} not found`);
    }
    
    return {
      ...accountConfig,
      serverConfig: domainConfig.serverConfig,
      webmail: domainConfig.serverConfig.webmail
    };
  },
  
  // Get email setup instructions for a user
  getSetupInstructions(domain, account) {
    const config = this.getEmailAccount(domain, account);
    const domainConfig = clientEmails[domain];
    
    return {
      emailAddress: config.email,
      displayName: config.name,
      
      // For email clients (Outlook, Apple Mail, etc.)
      incoming: {
        type: 'IMAP',
        server: domainConfig.serverConfig.imap.server,
        port: domainConfig.serverConfig.imap.port,
        encryption: domainConfig.serverConfig.imap.encryption,
        username: config.email,
        password: '[To be provided by administrator]'
      },
      
      outgoing: {
        type: 'SMTP',
        server: domainConfig.serverConfig.smtp.server,
        port: domainConfig.serverConfig.smtp.port,
        encryption: domainConfig.serverConfig.smtp.encryption,
        username: config.email,
        password: '[Same as incoming]',
        authRequired: true
      },
      
      // Quick setup for common clients
      quickSetup: {
        outlook: `Add Account > Manual Setup > IMAP`,
        appleMail: `Mail Settings > Accounts > Add Account > Other`,
        gmail: `Settings > Accounts > Add another email address`,
        mobile: `Email app > Add Account > IMAP`
      },
      
      // Webmail access
      webmail: {
        url: domainConfig.serverConfig.webmail.url,
        username: config.email,
        password: '[To be provided by administrator]'
      }
    };
  },
  
  // Generate email signature
  getEmailSignature(domain, account) {
    const config = this.getEmailAccount(domain, account);
    const domainConfig = clientEmails[domain];
    
    return `
${config.name}
${config.title}
${domainConfig.client}

📧 ${config.email}
📞 (845) 409-0692
🌐 https://www.gregpedromd.com

This email and any attachments may contain confidential and privileged information. 
If you are not the intended recipient, please notify the sender immediately and delete this email.
    `.trim();
  },
  
  // HTML signature for rich email clients
  getHTMLSignature(domain, account) {
    const config = this.getEmailAccount(domain, account);
    const domainConfig = clientEmails[domain];
    
    return `
<div style="font-family: Arial, sans-serif; font-size: 14px; color: #333;">
  <div style="margin-bottom: 10px;">
    <strong>${config.name}</strong><br>
    <span style="color: #666;">${config.title}</span><br>
    <span style="color: #0066cc; font-weight: 600;">${domainConfig.client}</span>
  </div>
  
  <div style="margin-bottom: 15px;">
    <span style="color: #666;">📧</span> <a href="mailto:${config.email}" style="color: #0066cc; text-decoration: none;">${config.email}</a><br>
    <span style="color: #666;">📞</span> <a href="tel:+18454090692" style="color: #0066cc; text-decoration: none;">(845) 409-0692</a><br>
    <span style="color: #666;">🌐</span> <a href="https://www.gregpedromd.com" style="color: #0066cc; text-decoration: none;">www.gregpedromd.com</a>
  </div>
  
  <div style="font-size: 11px; color: #999; border-top: 1px solid #eee; padding-top: 10px;">
    <em>This email and any attachments may contain confidential and privileged information. 
    If you are not the intended recipient, please notify the sender immediately and delete this email.</em>
  </div>
</div>
    `.trim();
  }
};

// Export specific configurations for easy access
export const gregPedroMD = clientEmails['gregpedromd.com'];