[build]
  command = "cd ../../payments && npm ci && npm run build"
  publish = "../../payments/dist"
  base = "frontend/bowerycreativefrontend"
  
[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200