[build]
  command = "npm ci && npm run build"
  publish = "dist"
  # Skip all builds - this app is now integrated into /payments
  ignore = "exit 0"
  
[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200